Repository OmeSatoFoundation/ome-doc, pull requests merged in 2023-06, with the labels that each got.

#149 [第3回][第5回][第6回] svgが存在する図をpngからsvgに置き換える
  03/contents/chap03_01.tex
  03/contents/chap03_02_2_15.tex
  03/contents/chap03_03_1.tex
  03/contents/chap03_03_5.tex
  03/images/chap03/directory_arc.svg
  03/images/chap03/douga.svg
  03/images/chap03/edge_trigger.svg
  03/images/chap03/ex3-15.svg
  03/images/chap03/ex3-2.svg
  03/images/chap03/image.svg
  03/images/chap03/oto.svg
  03/images/chap03/rpz-ir-sensor.svg
  03/images/chap03/text03-img001.png
  03/images/chap03/text03-img002.png
  03/images/chap03/text03-img003.png
  03/images/chap03/text03-img004.png
  03/images/chap03/text03-img005.png
  03/images/chap03/text03-img029.png
  03/images/chap03/text03-img031.png
  03/images/chap03/text03-img033.png
  03/llmk.toml
  03/text03.tex
  05/contents/chap05_04_1.tex
  05/contents/chap05_04_2.tex
  05/contents/chap05_04_3.tex
  05/images/chap05/IRproc.svg
  05/images/chap05/aircondition.svg
  05/images/chap05/control_signal.svg
  05/images/chap05/denkyu.svg
  05/images/chap05/fan.svg
  05/images/chap05/text.svg
  05/images/chap05/text05-img037.png
  05/images/chap05/text05-img037.svg
  05/images/chap05/text05-img038.png
  05/images/chap05/text05-img039.png
  05/images/chap05/text05-img040.png
  05/images/chap05/text05-img041.png
  05/images/chap05/text05-img042.png
  05/images/chap05/tv.svg
  05/llmk.toml
  05/text05.tex
  06/contents/chap06_01.tex
  06/contents/chap06_02.tex
  06/contents/chap06_05_3.tex
  06/images/chap06/Julius.svg
  06/images/chap06/JuliuswithHSP.svg
  06/images/chap06/text06-img002.png
  06/images/chap06/text06-img010.png
  06/images/chap06/text06-img011.png
  06/llmk.toml
  06/text06.tex
  Dockerfile
Labels: 第5回, 第6回, 第3回

#167 [第3回] [第5回] [第6回] llmk.toml内でlualatexのオプション指定にoptアトリビュートを使うように変更
  03/llmk.toml
  05/llmk.toml
  06/llmk.toml
Labels: 第5回, 第6回, 第3回

#201 第1回 軽微な修正
  01/contents/chap01_01.tex
  01/contents/chap01_02.tex
  01/contents/chap01_04.tex
  01/contents/chap01_08.tex
Labels: 第1回

#198 [第3回] issue #1で提案された修正の一部を反映
  03/contents/chap03_01.tex
  03/contents/chap03_03_1.tex
Labels: 第3回

#203 見落としていた図の表示を変更
  01/contents/chap01_01.tex
  01/contents/chap01_02.tex
Labels: 第1回

#202 [第3回] Issue #1で提案された修正案の一部を反映
  03/contents/chap03_03_3.tex
Labels: 第3回

#206 例題と問題の追加、その他微調整
  01/contents/chap01_01.tex
Labels: 第1回

#211 教材コピー手順を例題として設定
  01/contents/chap01_04.tex
Labels: 第1回

#212 不足パッケージの追加
  01/contents/chap01_preamble.tex
Labels: 第1回

#213 空欄を伴う問題について、空欄の高さを統一
  01/contents/chap01_01.tex
  01/contents/chap01_02.tex
  01/contents/chap01_preamble.tex
Labels: 第1回

#168 Expand vspace for answer placeholders
  03/contents/chap03_01.tex
  03/contents/chap03_02_2_10.tex
  03/contents/chap03_02_2_11.tex
  03/contents/chap03_02_2_12.tex
  03/contents/chap03_02_2_13.tex
  03/contents/chap03_02_2_15.tex
  03/contents/chap03_02_2_3.tex
  03/contents/chap03_02_2_5.tex
  03/contents/chap03_02_2_6.tex
  03/contents/chap03_02_2_7.tex
  03/contents/chap03_02_2_8.tex
  03/contents/chap03_02_2_9.tex
  03/contents/chap03_03_1.tex
  03/contents/chap03_03_2.tex
  03/contents/chap03_03_3.tex
  03/contents/chap03_03_4.tex
  03/contents/chap03_03_5.tex
  03/contents/chap03_03_6.tex
  texmf/tex/luatexja/omebook/omebook.sty
Labels: 第5回, 第6回, 第3回

#218 Fix 01:
  01/contents/chap01_01.tex
  01/contents/chap01_07.tex
Labels: 第1回

#219 レイアウトの変更
  01/contents/chap01_02.tex
Labels: 第1回

#217 第1回　スクリーンショットの軽微な修正
  01/contents/chap01_04.tex
  01/contents/chap01_08.tex
  01/text01-img/textbook-img142.png
  01/text01-img/textbook-img222.png
  01/text01-img/textbook-img224.png
  01/text01-img/textbook-img245.png
  01/text01-img/textbook-img246.png
Labels: 第1回

#195 例題番号が表示される演習用htmlのスクリーンショット差し替え
  01/text01-img/textbook-img146.png
  01/text01-img/textbook-img147.png
  01/text01-img/textbook-img148.png
  01/text01-img/textbook-img150.png
  01/text01-img/textbook-img151.png
  01/text01-img/textbook-img157.png
  01/text01-img/textbook-img158.png
  01/text01-img/textbook-img171.png
  01/text01-img/textbook-img174.png
  01/text01-img/textbook-img177.png
  01/text01-img/textbook-img181.png
  01/text01-img/textbook-img183.png
  01/text01-img/textbook-img184.png
  01/text01-img/textbook-img188.png
  01/text01-img/textbook-img190.png
  01/text01-img/textbook-img198.png
  01/text01-img/textbook-img204.png
  01/text01-img/textbook-img231.png
  01/text01-img/textbook-img236.png
  01/text01-img/textbook-img237.png
Labels: 第1回

#220 GIMP描画ツールの選択手順を変更し、簡易化
  01/contents/chap01_03.tex
  01/text01-img/textbook-img133.png
Labels: 第1回

#226 3.3 例題1-17のレイアウトの変更
  01/contents/chap01_03.tex
  01/text01-img/textbook-img124.png
  01/text01-img/textbook-img127.png
  01/text01-img/textbook-img129.png
Labels: 第1回

#233 第1回２時間目のスライドを追加
  01/slide01-2.tex
  01/slide01-img/slide02_001.png
  01/slide01-img/slide02_002.png
  01/slide01-img/slide02_003.png
  01/slide01-img/slide02_004.png
  01/slide01-img/slide02_005.png
  01/slide01-img/slide02_006.png
  01/slide01-img/slide02_007.png
  01/slide01-img/slide02_008.png
Labels: 第1回

#235 第1回 4時間目のスライドを追加、2時間目のスライドのissue#236の修正
  01/slide01-2.tex
  01/slide01-4.tex
  01/slide01-img/slide02_009.png
  01/slide01-img/slide02_010.png
  01/slide01-img/slide02_011.png
  01/slide01-img/slide02_012.png
  01/slide01-img/slide04_001.png
  01/slide01-img/slide04_002.png
  01/slide01-img/slide04_003.png
  01/slide01-img/slide04_004.png
  01/slide01-img/slide04_005.png
  01/slide01-img/slide04_006.png
  01/slide01-img/slide04_007.png
  01/slide01-img/slide04_008.png
  01/slide01-img/slide04_009.png
  01/slide01-img/slide04_010.png
  01/slide01-img/slide04_011.png
  01/slide01-img/slide04_012.png
  01/slide01-img/slide04_013.png
  01/slide01-img/slide04_014.png
  01/slide01-img/slide04_015.png
Labels: 第1回

#239 第１回、1時限目、3時限目スライドの追加
  01/slide01-1.tex
  01/slide01-3.tex
  01/slide01-img/slide03_001.png
  01/slide01-img/slide03_002.jpg
  01/slide01-img/slide03_003.JPG
  01/slide01-img/slide03_004.png
  01/slide01-img/slide03_005.png
Labels: 第1回

#238 第３回 typewriter型に変更
  03/contents/chap03_01.tex
  03/contents/chap03_02_2_10.tex
  03/contents/chap03_02_2_11.tex
  03/contents/chap03_02_2_12.tex
  03/contents/chap03_02_2_3.tex
  03/contents/chap03_02_2_5.tex
  03/contents/chap03_02_2_6.tex
  03/contents/chap03_02_2_7.tex
  03/contents/chap03_02_2_8.tex
  03/contents/chap03_02_2_9.tex
Labels: 第3回

#255 [第3回] Typo修正
  03/contents/chap03_02_2_8.tex
Labels: 第3回

#197 第三回の細かい修正
  03/contents/chap03_01.tex
  03/contents/chap03_03_1.tex
  03/contents/chap03_03_4.tex
  03/contents/chap03_03_5.tex
  03/contents/chap03_03_6.tex
Labels: 第3回

#256 指摘箇所の修正
  03/contents/chap03_01.tex
Labels: 第3回

#232 [第5回] 赤外線受信デバイスをlirc1に変更
  05/contents/chap05_04_3.tex
Labels: 第5回

#259 adopt the install methodology of texlive 2023
  Dockerfile
Labels: buildproc

#261 change directory name language of xdg-user-dirs
  03/contents/chap03_01.tex
Labels: 第3回

#260 leafpadをmousepadに変更
  03/contents/chap03_02_2_9.tex
Labels: 第3回

#265 [第３回]　小学５年生以降で習う漢字にルビ振り
  03/contents/chap03_01.tex
  03/contents/chap03_02_2_11.tex
  03/contents/chap03_02_2_12.tex
  03/contents/chap03_02_2_13.tex
  03/contents/chap03_02_2_14.tex
  03/contents/chap03_02_2_15.tex
  03/contents/chap03_02_2_3.tex
  03/contents/chap03_02_2_4.tex
  03/contents/chap03_02_2_5.tex
  03/contents/chap03_02_2_6.tex
  03/contents/chap03_02_2_7.tex
  03/contents/chap03_02_2_8.tex
  03/contents/chap03_02_2_9.tex
  03/contents/chap03_03_1.tex
  03/contents/chap03_03_2.tex
  03/contents/chap03_03_3.tex
  03/contents/chap03_03_4.tex
  03/contents/chap03_03_5.tex
  03/contents/chap03_03_6.tex
  03/contents/chap03_03_7.tex
Labels: 第3回

#267 [第3回] 付け忘れたaddquizマクロの追加
  03/contents/chap03_01.tex
Labels: 第3回

#266 [第3回] RPi3の画像をRPi400に差し替える
  03/contents/chap03_03_1.tex
  03/images/chap03/how_to_install_bme280.jpg
  03/images/chap03/led_emission_demo.png
Labels: 第3回

#268 第3回 教科書のはじめに教材をコピーすることを追記
  03/contents/chap03_01.tex
Labels: 第3回
