Repository OmeSatoFoundation/ome-doc, pull requests merged in 2023-09, with the labels that each got.

#378 7回、8回の修正
  07/text07.tex
  08/text08.tex
Labels: 優先度高, 第7回, 第8回

#374 [第6回] 図中のJtalkをJTalkに修正
  06/images/chap06/text06-img011.svg
Labels: 第6回

#382 第8回 leafppad->mousepad
  08/text08.tex
Labels: 第8回

#386 第7，8回　#349の修正漏れの修正、~抜けの修正、/home/piを~に変更
  07/text07.tex
  08/text08.tex
Labels: 第7回, 第8回

#417 第8回スライドの作成、第7回残りの問題のスライドの追加
  07/slide07-4.tex
  07/text07.tex
  08/slide08-1.tex
  08/slide08-2.tex
  08/slide08-3.tex
  08/slide08-4.tex
  08/slide08-img/raspberry.png
  08/slide08-img/slide08-img001.png
  08/slide08-img/slide08-img002.png
  08/slide08-img/slide08-img003.png
  08/slide08-img/slide08-img004.png
  08/slide08-img/slide08-img005.png
  08/slide08-img/slide08-img006.png
  08/slide08-img/slide08-img007.png
  08/slide08-img/slide08-img008.png
  08/text08.tex
Labels: 第7回, 第8回
