Repository OmeSatoFoundation/ome-doc, pull requests merged in 2023-08, with the labels that each got.

#318 第５回の教科書にるびを振る
  05/contents/chap05_01.tex
  05/contents/chap05_02_1.tex
  05/contents/chap05_02_3.tex
  05/contents/chap05_03_1.tex
  05/contents/chap05_03_2.tex
  05/contents/chap05_03_3.tex
  05/contents/chap05_03_4.tex
  05/contents/chap05_03_5.tex
  05/contents/chap05_03_6.tex
  05/contents/chap05_03_7.tex
  05/contents/chap05_03_8.tex
  05/contents/chap05_04_1.tex
  05/contents/chap05_04_2.tex
  05/contents/chap05_04_3.tex
  05/contents/chap05_04_4.tex
  05/contents/chap05_04_5.tex
  05/contents/chap05_05_1.tex
  05/contents/chap05_05_10.tex
  05/contents/chap05_05_2.tex
  05/contents/chap05_05_3.tex
  05/contents/chap05_05_4.tex
  05/contents/chap05_05_5.tex
  05/contents/chap05_05_6.tex
  05/contents/chap05_05_8.tex
  05/contents/chap05_05_9.tex
Labels: 第5回

#315 第六回の body font size を 12 pt に
  03/text03.tex
  05/text05.tex
  06/text06.tex
  texmf/tex/luatexja/omebook/omebook.sty
Labels: 第6回

#350 第７，８回 例題問題番号のカウンタ設定、一部問題に変更
  07/text07.tex
  08/text08.tex
Labels: 第7回, 第8回

#376 ~/ome/0x から ~/0xへの表記、画像の変更
  07/text07-img/ome7-img033.png
  07/text07-img/ome7-img034.png
  07/text07-img/ome7-img038.png
  07/text07.tex
  08/text08-img/textbook-img002.png
  08/text08-img/textbook-img003.png
  08/text08-img/textbook-img004.png
  08/text08-img/textbook-img005.png
  08/text08-img/textbook-img006.png
  08/text08-img/textbook-img015.png
  08/text08-img/textbook-img020.png
  08/text08-img/textbook-img022.png
  08/text08-img/textbook-img031.png
  08/text08-img/textbook-img032-1.png
  08/text08-img/textbook-img032-2.png
  08/text08-img/textbook-img032.png
  08/text08-img/textbook-img057.png
  08/text08-img/textbook-img063.png
  08/text08-img/textbook-img064.png
  08/text08-img/textbook-img065.png
  08/text08-img/textbook-img066.png
  08/text08.tex
Labels: 第7回, 第8回

#377 第7回　表記の軽微な修正
  07/text07-img/ome7-img023.png
  07/text07.tex
Labels: 第7回
