Repository OmeSatoFoundation/ome-doc, pull requests merged in 2024-08, with the labels that each got.

#596 第６回 授業スライド スタイル変更
  06/slide06.tex
Labels: 第6回, 2024

#594 第５回 授業スライド スタイル変更
  05/slide05.tex
  05/slide_contents/digital_input_device.tex
  05/slide_contents/exe.tex
Labels: 第5回, 2024

#585 use eom instead of gpicview from bookworm
  03/contents/chap03_430_ChallengeGIFAnime.tex
Labels: bookworm

#600 距離センサーの式の訂正
  05/contents/chap05_03_5.tex
  05/contents/chap05_05_9.tex
Labels: 第5回, 2024

#603 【第６回】gettimeの実行例の更新
  06/contents/chap06_04_3.tex
Labels: 第6回, 2024

#606 第5回、第7回 シールカード
  cards/cards.tex
Labels: 第5回, 第7回

#608 第５回スライド微調整
  05/slide_contents/digital_input_device.tex
  05/slide_contents/fabo.tex
  05/slide_contents/ir.tex
  05/slide_contents/sensor_application.tex
  05/update.pdf
Labels: 第5回, 2024

#609 第5回、第7回　画像変更
  cards/cards.tex
Labels: 第5回, 第7回
