Repository OmeSatoFoundation/ome-doc, pull requests merged in 2024-05, with the labels that each got.

#456 第３回：注意書きの追加 #79
  03/contents/chap03_03_1.tex
Labels: 第3回

#465 第5回 digin.hsp、5.9の冒頭文を修正
  05/contents/chap05_03_4.tex
Labels: 第5回

#464 [第5回] ルビが表の枠と重なっている部分の修正
  05/contents/chap05_01.tex
  05/contents/chap05_02_3.tex
  05/contents/chap05_03_1.tex
  05/contents/chap05_05_1.tex
  05/contents/chap05_05_10.tex
  05/contents/chap05_05_11.tex
  05/contents/chap05_05_2.tex
  05/contents/chap05_05_3.tex
  05/contents/chap05_05_4.tex
  05/contents/chap05_05_5.tex
  05/contents/chap05_05_6.tex
  05/contents/chap05_05_7.tex
  05/contents/chap05_05_8.tex
  05/contents/chap05_05_9.tex
  05/text05.tex
Labels: 第5回, 2024

#485 [第5回] 赤外線送受信のまとめの修正
  05/contents/chap05_04_5.tex
Labels: 第5回, 2024

#486 Webカメラで赤外線を確認できる説明の追加 Fix#115
  05/contents/chap05_04_1.tex
  05/images/chap05/infrared_rays_led.svg
Labels: 第5回
