Repository OmeSatoFoundation/ome-doc, pull requests merged in 2024-06, with the labels that each got.

#508 【第2回】文章の修正とルビの追加
  02/contents/chap02_01.tex
  02/contents/chap02_02.tex
  02/contents/chap02_03_1.tex
  02/contents/chap02_03_10.tex
  02/contents/chap02_03_2.tex
  02/contents/chap02_03_3.tex
  02/contents/chap02_03_4.tex
  02/contents/chap02_03_5-7.tex
  02/contents/chap02_03_8.tex
  02/contents/chap02_03_9.tex
  02/contents/chap02_04_1-4.tex
  02/contents/chap02_04_5.tex
  02/contents/chap02_04_6.tex
  02/contents/chap02_05_1-5.tex
  02/contents/chap02_05_6.tex
Labels: 第2回, 2024

#509 【第4回】文章の修正とルビの追加
  04/contents/chap04_00.tex
  04/contents/chap04_01.tex
  04/contents/chap04_02.tex
  04/contents/chap04_03.tex
  04/contents/chap04_04.tex
  04/contents/chap04_05.tex
  04/contents/chap04_06.tex
  04/contents/chap04_07.tex
  04/contents/chap04_09.tex
  04/contents/chap04_10.tex
  04/contents/chap04_12.tex
  04/contents/chap04_13.tex
  04/contents/chap04_15.tex
  04/contents/chap04_16.tex
  04/contents/chap04_17.tex
  04/contents/chap04_18.tex
  04/contents/chap04_19.tex
  04/contents/chap04_21.tex
  04/contents/chap04_22.tex
  04/contents/chap04_23.tex
  04/contents/chap04_24.tex
  04/contents/chap04_25.tex
  04/contents/chap04_26.tex
  04/contents/chap04_27.tex
  04/contents/chap04_28.tex
  04/contents/chap04_29.tex
  04/contents/chap04_32.tex
Labels: 第4回, 2024

#503 【第3回】trコマンドについての説明と例題の追加
  03/contents/chap03_150_AdvancedCommands.tex
Labels: 第3回, 2024

#507 slide03後半
  03/images/chap03/button_push.png
  03/images/chap03/sensors_name.png
  03/slide_contents/sensorboard.tex
Labels: 第3回

#506 IR ロボットに関する注記を追加
  05/contents/chap05_04_3.tex
  05/contents/ir_notice.tex
  05/text05.tex
Labels: 第5回

#515 slide03前半作成途中
  03/slide_contents/shell_command.tex
Labels: 第3回

#518 echoコマンドの説明を追加
  03/contents/chap03_150_AdvancedCommands.tex
Labels: 第3回

#519 第3回 スライド 細かい修正
  03/slide_contents/sensorboard.tex
Labels: 第3回

#524 【第3回】trコマンドについての説明と例題の追加
  03/contents/chap03_150_AdvancedCommands.tex
Labels: 第3回

#526 use tilde instead of /home/pi/ to indicate home directory in sed section
  03/contents/chap03_150_AdvancedCommands.tex
Labels: 第3回

#527 ヒント中の教科書参照ページの修正
  03/contents/chap03_210_SensorBoard.tex
  03/contents/chap03_220_LEDBlinker.tex
Labels: 第3回
